-- Generated from Hibernate's own schema export, not hand-written.
--
-- The timestamp columns are the reason: Hibernate 6 maps java.time.Instant to TIMESTAMP_UTC, which the
-- H2 dialect renders as `timestamp(6) with time zone`. A hand-guessed `TIMESTAMP(6)` looks right and
-- fails `spring.jpa.hibernate.ddl-auto=validate` at startup.
--
-- `provider` is a plain VARCHAR with no CHECK constraint on purpose: supporting one more broker should
-- not require a schema migration. The application is the only writer and always stores enum names.

CREATE TABLE connection_profile (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR(120)                NOT NULL,
    provider            VARCHAR(32)                 NOT NULL,
    host                VARCHAR(255),
    port                INTEGER,
    username            VARCHAR(255),
    password_cipher     VARCHAR(2048),
    broker_url_override VARCHAR(1024),
    queue_manager_name  VARCHAR(48),
    channel             VARCHAR(64),
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_connection_profile_name UNIQUE (name)
);
