-- Generated from Hibernate's own schema export, for the same reason as V1: java.time.Instant maps to
-- TIMESTAMP_UTC, which the H2 dialect renders as `timestamp(6) with time zone`. A hand-guessed
-- `TIMESTAMP(6)` looks right and fails `spring.jpa.hibernate.ddl-auto=validate` at startup.
--
-- `kind` carries no CHECK constraint, exactly as `connection_profile.provider` does not: adding a
-- destination kind should not require a schema migration, and the application is the only writer.
--
-- The foreign key and the index are hand-added — Hibernate's export does not emit them, because the
-- entity holds a plain connection_profile_id column rather than a @ManyToOne. `validate` does not check
-- constraints either way, so these are ours to declare, and ON DELETE CASCADE is the whole reason for
-- declaring the first one: deleting a connection must take its remembered destinations with it without
-- the application having to remember to.
--
-- The unique constraint is case-SENSITIVE, unlike connection_profile.name. Queue and topic names are
-- case-sensitive on all four providers, so ORDERS and orders are two different destinations.
--
-- V1 and V2 are deliberately untouched: they have already run against every existing data directory.

CREATE TABLE saved_destination (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    connection_profile_id BIGINT                      NOT NULL,
    name                  VARCHAR(512)                NOT NULL,
    kind                  VARCHAR(16)                 NOT NULL,
    pinned                BOOLEAN                     NOT NULL,
    open_count            BIGINT                      NOT NULL,
    last_opened_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_saved_destination_connection_name UNIQUE (connection_profile_id, name),
    CONSTRAINT fk_saved_destination_connection FOREIGN KEY (connection_profile_id)
        REFERENCES connection_profile (id) ON DELETE CASCADE
);

-- Covers the only query this table has: "the remembered destinations for one connection, newest first".
CREATE INDEX ix_saved_destination_connection_opened
    ON saved_destination (connection_profile_id, last_opened_at DESC);
