-- Generated from Hibernate's own schema export, for the same reason as V1 and V3: java.time.Instant maps
-- to TIMESTAMP_UTC, which the H2 dialect renders as `timestamp(6) with time zone`. A hand-guessed
-- `TIMESTAMP(6)` looks right and fails `spring.jpa.hibernate.ddl-auto=validate` at startup.
--
-- The VARCHAR lengths mirror the entity's @Column(length=…): a message body is stored verbatim, so the
-- payload column is deliberately large. `properties_json` holds the custom properties/headers map as a
-- JSON object string rather than a child table this feature would not otherwise need.
--
-- There is NO unique constraint on (connection_profile_id, destination_name, label). Two kinds of row
-- live here: a null `label` is an automatic history entry and must be allowed to repeat, while a named
-- request is kept unique per destination by the service (upsert by label). H2's handling of NULLs in a
-- unique index is exactly the sort of thing that is a schema migration to change later, so the rule is
-- the application's, matching how connection_profile.provider carries no CHECK constraint either.
--
-- The foreign key and the index are hand-added — Hibernate's export does not emit them, because the
-- entity holds a plain connection_profile_id column rather than a @ManyToOne. `validate` does not check
-- constraints either way, so these are ours to declare, and ON DELETE CASCADE is the reason for the
-- first: deleting a connection must take its remembered requests with it.
--
-- V1, V2 and V3 are deliberately untouched: they have already run against every existing data directory.

CREATE TABLE saved_request (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    connection_profile_id BIGINT                      NOT NULL,
    destination_name      VARCHAR(512)                NOT NULL,
    label                 VARCHAR(120),
    payload               VARCHAR(1048576)            NOT NULL,
    properties_json       VARCHAR(65536)              NOT NULL,
    message_key           VARCHAR(1024),
    message_type          VARCHAR(16),
    target_client         VARCHAR(16),
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_saved_request_connection FOREIGN KEY (connection_profile_id)
        REFERENCES connection_profile (id) ON DELETE CASCADE
);

-- Covers the only query this table has: "the remembered requests for one destination, newest first".
CREATE INDEX ix_saved_request_connection_destination_created
    ON saved_request (connection_profile_id, destination_name, created_at DESC);
